# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0766d7ac47009e5aaaf4f0ebe89d7d77a3a3158a744c18530d37971e257d273aa9ede9bc43b47fe18f143f223b586896c2e992bccee75bcf1c8860fefe1e9fb2

test:
  secret_key_base: 024c58816eb3571f21a662b2a75ec29825a38ba261101c68e5e57e59e264a5d8d2c029a381f5d2916a547adb266fb35fb4664b758a7e1d39643816d6fc11d1ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
